# Generated by Django 4.2.2 on 2023-10-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
